name: Builder

env:
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs"
  ARCHITECTURES: '["amd64", "aarch64"]'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    name: Check for changed addons
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7.0.1

      - name: Get changed files
        id: changed_files
        uses: Ana06/get-changed-files@v2.3.0

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)

          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  init-build:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.changed == 'true'
    name: Init builds
    outputs:
      matrix: ${{ steps.update-matrix.outputs.updated_matrix }}
      push: ${{ steps.should_push.outputs.push }}
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Decide to push
        id: should_push
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Push the image"
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "Do not push the image"
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Get information for ${{ matrix.addon }}
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Format build matrix parameters
        id: parameters
        run: |
          OWNER="${{ github.repository_owner }}"
          LOWER_OWNER="${OWNER,,}"

          echo "registry-prefix=ghcr.io/$LOWER_OWNER" >> $GITHUB_OUTPUT

          ADDON="${{ matrix.addon }}"
          HYPHENATED_ADDON="${ADDON//_/-}"

          echo "image-name=$HYPHENATED_ADDON" >> $GITHUB_OUTPUT

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ steps.parameters.outputs.image-name }}
          registry-prefix: ${{ steps.parameters.outputs.registry-prefix }}

      - name: Inject addon and version into matrix
        id: update-matrix
        run: |
          INPUT_JSON='${{ steps.matrix.outputs.matrix }}'
          ADDON_VAL='${{ matrix.addon }}'
          VERSION_VAL='${{ steps.info.outputs.version }}'
          VERSION_VAL=${VERSION_VAL//\"/}
          
          UPDATED_JSON=$(echo "$INPUT_JSON" | jq -c --arg addon "$ADDON_VAL" --arg version "$VERSION_VAL" '.include |= map(. + {addon: $addon, version: $version})')
          
          echo "updated_matrix=$UPDATED_JSON" >> $GITHUB_OUTPUT


  build:
    needs: init-build
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init-build.outputs.matrix) }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ matrix.version }}
            latest
          push: ${{ needs.init-build.outputs.push }}
          version: ${{ matrix.version }}

  manifest:
    name: Publish multi-arch manifest for ${{ matrix.addon }} add-on
    needs: [init, init-build, build]
    runs-on: ubuntu-latest
    if: needs.init-build.outputs.push == 'true'
    permissions:
      id-token: write 
      packages: write 
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    steps:
      - name: Get information for ${{ matrix.addon }}
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Cleanup version
        id: version
        run: |
          VERSION_VAL='${{ steps.info.outputs.version }}'
          VERSION_VAL=${VERSION_VAL//\"/}

          echo "version=$VERSION_VAL" >> $GITHUB_OUTPUT

      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.addon }}
          image-tags: |
            ${{ steps.version.outputs.version }}
            latest